package com.utils;

/**
 * @Author:Andrew
 * @Description:封装测试用例
 * @Date 2018/1/3 0003
 */
public class AutomaticGenerated {
    /**
     * @Desrciption:生成测试用例
     * */
    /* public static void AutoGeneratedCase(UICaseStep uiCaseStep){

     }*/
}
